### ISSUE TITLE
Native Notebooks - Language set not maintained

### ISSUE THREAD

**Issue by claudiaregio** [dotnet/interactive#1309]
Try opening notebook attached with the .NET interactive extension. 
The language for both cells is set to C# (Not C# .NET Interactive and F# .NET Interactive) 
[.NETtest.zip](https://github.com/dotnet/interactive/files/6387025/default.NETtest.zip)

![image](https://user-images.githubusercontent.com/19276747/116298449-54b0e200-a751-11eb-97ef-17f03889923e.png)

**Comment by claudiaregio** [comment]
@jonsequitur could this be a dupe of https://github.com/dotnet/interactive/issues/1038?

**Comment by jonsequitur** [comment]
@claudiaregio The symptom is the same but the cause is different. We do preserve the cell metadata now.

**Comment by jhoneill** [comment]
Getting it here too: the v1.0.2227031 update did this to multiple notebooks, if I set the cells to the right type it fixes the problem - it seems to be failing to read types correctly from ipynbs created with earlier versions, but saves OK  but I can't see what is changing in the underlying JSON.

**Comment by jonsequitur** [comment]
Is this also broken for you in VS Code non-Insiders?

**Comment by jhoneill** [comment]
I've got quite the matrix here - one machine has the anaconda / Jupyter combo and one doesn't, and both machines have insiders _and_ stable VS Code.  
I'm on the no-Python machine at moment, and with code *stable* + plugin v1.0.2227030  `#!about` reporting    
```
Version: 1.0.222703+320f05fcad9ac2e5360e649acf2cb49e56e731c8
Build date: 2021-04-28T11:39:58.1641221Z
```
Some of my notebooks were happy; others open and look like this   
![image](https://user-images.githubusercontent.com/16209593/116440451-6e812080-a848-11eb-8ac4-f70c1926c357.png)

The "Happy"  ones show `C#` initially and quickly change to the right cell type. (Some which *were* happy were triggered to remain on `C#`  by using `.Net interactive: Open notebook` once on an "unhappy" one and then did this however they were opened, but they were happy again if I closed and re-opened _code_. This makes it difficult to know if the problem is the state VS code is in or something in the IPYNB file). 

If I choose the .net interactive kernel with an "unhappy" one ...   
![image](https://user-images.githubusercontent.com/16209593/116440938-e18a9700-a848-11eb-96a8-305364054690.png)    
- it's the only choice - the cells change from `C#` to `C# (.Net Interactive)` things remain good if the file is saved and re-opened. It crossed my mind that the open process could select the kernel when there is only one, but there is no guarantee it would be right, so better not to!   

![image](https://user-images.githubusercontent.com/16209593/116441184-21ea1500-a849-11eb-9a35-43a2d5ca5959.png)

Rolling back the ipynb causes things to go back to `C#` so it is a change in the file which is fixing it. I can't isolate that change but it looks like recognizing the kernel fails for some files and all their cells remain as C#. Others open as C# and after a moment become the correct cell types (presumably when the kernel is set)   

re: `Jupyter Server: local` on the status bar:  I don't get .net Interactive on `View: Reopen notebook with` or right-click file , `open with` 
![image](https://user-images.githubusercontent.com/16209593/116443056-1992d980-a84b-11eb-882d-40e0ab802c93.png)

Is this an intentional change - it works fine, it just looks like some work has been discarded.

**Comment by jhoneill** [comment]
**Additional**
My notebooks are in GIT so after getting everything working on the Python-less machine I've moved the Pythonated one. 
In the comment above select notebook kernal could only see the .Net Interactive kernel. 
This machine also sees all the kernels know to Jupyter server if I start it from anaconda.

![image](https://user-images.githubusercontent.com/16209593/116579364-39d59d80-a90a-11eb-8910-127a27241be9.png)

A work book which was happy on the other machine goes to all `C#` cells here. But after selecting .net interactive from the list above it changes from `c#` to  `c# (.net interactive)`
![image](https://user-images.githubusercontent.com/16209593/116579008-e1060500-a909-11eb-9bb8-a0712b994906.png)

From here, **behaviour diverges from the other machine.** If I save and reload, the selected kernel goes back to C#, and the cells label themselves as `C#`  and the version reported by `#!about` changes from matching the Code extension to the stable version of .NET Interactive currently bound to Jupyter. 
 ![image](https://user-images.githubusercontent.com/16209593/116579664-83be8380-a90a-11eb-9a1a-1941c6f83c3d.png)

![image](https://user-images.githubusercontent.com/16209593/116579835-b1a3c800-a90a-11eb-95f4-b358212a4344.png)

If I set the kernel to the Jupyter-Style `Net (PowerShell)` then anything I set the cell to  works as PowerShell  - below I have set XML but C# would work 
![image](https://user-images.githubusercontent.com/16209593/116581205-fed46980-a90b-11eb-97c5-bc1a652a7ba9.png)
And when I save and re-open all the cells become `PowerShell` (Jupyter style). Now if I change the Kernel to .Net Interactive, close and reload instead of rolling back to `C#`, the cells become `PowerShell`. 
This defaulting-to-the-last-kernel behavior  is very similar to #1315  except that it applies to the non-insiders build, and I don't get a prompt to change controller / kernel on opening.

**Comment by amunger** [comment]
This may now be fixed in VSCode insiders as part of https://github.com/microsoft/vscode/issues/140673, although hopefully it's not causing a different issue by conflicting with the current metadata:
```
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "dotnet_interactive": {
     "language": "csharp"
    },
    "vscode": {
     "languageId": "dotnet-interactive.csharp"
    }
   },
```

**Comment by claudiaregio** [comment]
This is currently still an issue with the latest stable releases. However, I noticed that if I open it the first time, I see C# both times. If I try one or two more times, then I see C# and F# in the language picker

**Comment by jonsequitur** [comment]
The behavior we're seeing currently is that the language settings are maintained but the file is opening by default using the Jupyter kernel, which doesn't have these languages registered. Switching to the .NET Interactive extension resolves the correct languages, so it appears the cell-specific language metadata was preserved correctly, but on first open for a given file, the wrong extension is handling the `.ipynb`.
