### ISSUE TITLE
HTML Input DOM Events Bubble Up To Notebook And Are Handled There

### ISSUE THREAD

**Issue by collinkruger** [dotnet/interactive#2020]
### Describe the bug
Hi, .NET Interactive Team!
1. Add an HTML input element to an output cell.
2. Add some text to it (ex: focus the input element, and press the 'b' key).
3. The notebook interprets the event as a keyboard shortcut.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

**Version:** 1.0.325601+1743a009db9b6b64e33146e1681731acc785a7cf
**Library version:** 1.0.0-beta.22256.1+1743a009db9b6b64e33146e1681731acc785a7cf
**Build date:** 2022-05-11T16:42:03.3294298Z

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [X] Linux (Please specify distro) Ubuntu 22.04
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code (.NET Interactive Notebook)
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/23742214/169099433-b889fc0f-cffc-45b3-935c-a758a0f2ed55.png)

This is a minimal example. Focus the input box, then press the 'b' key. A new cell will be created.
![image](https://user-images.githubusercontent.com/23742214/169099072-ad550aec-353b-44ce-b968-e04f8037e7a6.png)

The same behavior can be observed when using SandDance.
![image](https://user-images.githubusercontent.com/23742214/169099376-d4070534-44ab-4536-8db8-cb26c2d9ca8f.png)

**Comment by jonsequitur** [comment]
Wow, that's a good one! 

@rebornix, any ideas what's happening here?

**Comment by PawelStadnicki** [comment]
Hi, I noticed it as well a long time ago, but today I decided to write this comment as I need it to be addressed.

A lot of notebooks' keyboard shortcut overlaps,  "M" changes the code cell to markup, which completely brakes the UI.

Despite there is an option to mitigate these shortcuts by writing own vs code extensions, it most likely should be done on the vs code notebook API level via some new keyboard _when clause_ or sth similar.
I guess it requires the cell output to be explicitly recognized by vs code, not sure how difficult it would be.

In particular, I have plenty of HTML apps being displayed as output cells,
 and to make it work, I have to DELETE notebook keyboard shortcuts, as I cannot type almost anything in HTML inputs.

Fine by me, but when I publish my work, I doubt users will want to do the same...

![image](https://user-images.githubusercontent.com/56049414/214690767-dcdf3148-2da0-494c-bf26-821423e0a761.png)

Appreciate any feedback on this one. Polyglot Notebooks are amazing!

**Comment by jonsequitur** [comment]
Thanks for the kind words and for the additional use case example!

I think all kinds of widget scenarios will be effectively blocked by this. I'll try to find out more about how we can address this.

**Comment by rebornix** [comment]
@PawelStadnicki did you run into the keybinding issue when typing in input boxes in outputs or you have run into the problem in other scenarios too? We have fixed the input box typing issue in VS Code Insiders, it will be available to VS Code Stable next week. I'd love to know if there is anything else we can do to improve it.

**Comment by PawelStadnicki** [comment]
Thank you very much. I will confirm on Sunday as I just started trip. Yes,
only input of the cell.

czw., 26 sty 2023, 12:39 AM użytkownik Peng Lyu ***@***.***>
napisał:

**Comment by PawelStadnicki** [comment]
It looks like this issue is still present.
I fully reinstalled VS Code Insiders, keyboard binding looks like this:

![image](https://user-images.githubusercontent.com/56049414/215414946-d44ca663-569c-404f-9c22-07c4ff281148.png)
Whenever I type one of them in the input, my cell output reacts and breaks accordingly (M changes to markup, X deletes the output, etc).

Version: 
![image](https://user-images.githubusercontent.com/56049414/215413887-1ac4284c-a71f-4853-a70c-016f53d0f2b6.png)
![image](https://user-images.githubusercontent.com/56049414/215414102-cbff4abd-f034-460d-8a76-d0062e06ed00.png)

My Html output is generated from F# cell (either as pain display or via proper custom Formatter).
I also tried plain input as Html markup, and it is the same:

![image](https://user-images.githubusercontent.com/56049414/215415403-56693109-f03e-496b-ba26-e572e1ae80ea.png)

**Comment by jonsequitur** [comment]
For folks who are hitting this, one workaround that seems to be working for me is to add `onkeydown="event.stopPropagation()"` to your `input` elements.
