### ISSUE TITLE
Unable to find package Azure.Identity. No packages exist with this id in source(s): C:\Program Files\dotnet\sdk\7.0.403\FSharp\library-packs

### ISSUE THREAD

**Issue by onionhammer** [dotnet/interactive#3289]
### Describe the bug
When I run
```CSX
#r "nuget: Azure.Identity, 1.10.1"
```

I get 

```
\nuget\Projects\3360--a4a684bf-6f1e-44e7-8ba4-aff69777dc2d\Project.fsproj : error NU1101: Unable to find package Azure.Identity. No packages exist with this id in source(s): C:\Program Files\dotnet\sdk\7.0.403\FSharp\library-packs
```

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
I'm not able to reproduce this issue and I don't think it would be an issue with .NET Interactive since it uses whatever NuGet configurations you have on your machine. 

Are you able to restore a project referencing this package?

**Comment by onionhammer** [comment]
> Are you able to restore a project referencing this package?

Yes, only the notebook was affected.

**Comment by jonsequitur** [comment]
If you run `dotnet nuget list source` in the same directory where the notebook is located, what do you see?

**Comment by onionhammer** [comment]
> If you run `dotnet nuget list source` in the same directory where the notebook is located, what do you see?

```
\tools\notebooks> dotnet nuget list source
Registered Sources:
  1.  nuget [Enabled]
      https://api.nuget.org/v3/index.json
```

**Comment by ptrushin** [comment]
I have the same error, when current dotnet version is 6 (dotnet --version in folder with file). When i add global.json like
{
  "sdk": {
    "version": "7.0.400"
  }
}
all is ok

**Comment by jonsequitur** [comment]
.NET 8 support was released today. Please update and let us know if it resolves the issue.

**Comment by pimbrouwers** [comment]
Back to the 7.* SDK is probably easiest. Just use a localized global.json
and away you go.

**Comment by pimbrouwers** [comment]
You have the details exactly correct on how the script provides access to nuget resources via the file system, post http request. 

For repro, we can peel this back even further than the notebook. It's just a wrapper around the core scripting environment. 

The simplest repro would be:
1. Create a file named `NugetPackageTest.fsx`
2. On line 1 of the file enter `#r "nuget:[package]"`
4. Execute script `dotnet fsi NugetPackageTest.fsx`

**Comment by pimbrouwers** [comment]
Interestingly, this error does not occur if you're running as Administrator on Windows 11.

**Comment by pimbrouwers** [comment]
In my case this was fixed by eliminating spaces from NuGet source names. See: https://github.com/dotnet/fsharp/issues/16071

**Comment by onionhammer** [comment]
Bump: This is still an error, havent been able to use notebooks for a good long while now.

nuget\Projects\39208--31424aae-586c-48f9-a5df-2f4f9b768563\Project.fsproj : error NU1101: Unable to find package Azure.Core. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, C:\Program Files\dotnet\sdk\8.0.200\FSharp\library-packs

**Comment by KevinRansom** [comment]
Hey, I'm going to work on this, sorry it's taken so long to get around to it, I've been busy on other stuff.

It will be managed by this issue:  https://github.com/dotnet/fsharp/issues/16071

When it's fixed, the fix will flow through to notebooks, but they only take publicly available FSHarps, so it may take a while to flow.
